-- Up Migration

ALTER TABLE tokens REPLICA IDENTITY FULL;
ALTER TABLE orders REPLICA IDENTITY FULL;
ALTER TABLE fill_events_2 REPLICA IDENTITY FULL;
ALTER TABLE collections REPLICA IDENTITY FULL;
ALTER TABLE nft_transfer_events REPLICA IDENTITY FULL;

-- Down Migration

ALTER TABLE tokens REPLICA IDENTITY DEFAULT;
ALTER TABLE orders REPLICA IDENTITY DEFAULT;
ALTER TABLE fill_events_2 REPLICA IDENTITY DEFAULT;
ALTER TABLE collections REPLICA IDENTITY DEFAULT;
